apiVersion: v1
kind: ConfigMap
metadata:
 name: nginx-config
 namespace: default
data:
 index.html: |
   <html>
   <head><title>Hello World NEW</title></head>
   <body>
   <h1>Hello World NEW</h1>
   </body>
   </html
