apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: html-app
  template:
    metadata:
      labels:
        app: html-app
    spec:
      containers:
        - name: nginx
          image: your-docker-repo/html-app:latest  # Replace with your image
          ports:
            - containerPort: 80
