apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: html-app
  template:
    metadata:
      labels:
        app: html-app
    spec:
      containers:
        - name: nginx
          image: galshraga/simple-webserver:50bed0b906c7baa2201d848155e6076c76ade901
          ports:
            - containerPort: 80
